apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps-nginx-persistent-test
  name: nginx-persistent-test
  annotations: {}
labels:
  app: nginx-persistent-test
spec:
  selector:
    matchLabels:
      app: nginx-persistent-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-persistent-test
    spec:
      containers:
        - name: container
          image: 'nginx:latest'
          ports:
            - containerPort: 80
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
